version: '3.8'

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=changethis123
      - BACKEND_CORS_ORIGINS=https://seyramgabriel.com,http://localhost,http://localhost:5173,https://localhost,https://localhost:5173
      - SECRET_KEY=changethis123
      - FIRST_SUPERUSER=devops@hng.tech
      - FIRST_SUPERUSER_PASSWORD=devops#HNG11
      - USERS_OPEN_REGISTRATION=True

  frontend:
    build: ./frontend
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
  #   depends_on:
  #    - backend

  # nginx:
  #   build: .
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /var/lib/letsencrypt:/var/lib/letsencrypt
  #   depends_on:
  #     - frontend
  #     - backend
  #     - proxy-manager
  #     - adminer

  nginx:
    image: nginx:latest
#    volumes:
    #  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #  - ./nginx/ssl:/etc/nginx/ssl
    #  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #  - ./nginx/letsencrypt:/etc/letsencrypt
    #  - ./nginx/ssl:/etc/nginx/ssl
    #  - ./nginx/html:/usr/share/nginx/html
  #  ports:
  #    - "80:80"
  #    - "443:443"
    depends_on:
      - frontend
      - backend

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
#     - "81:81"
     - "8090:81" # For accessing NPM UI
#     - "80:80"
#     - "443:443"
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
      - ./proxy/ssl:/etc/nginx/ssl
    depends_on:
      - nginx
      - adminer
volumes:
  postgres_data:
